/**
 * * * * Amisha Prasad // First and Last Name
 * * * * aprasa14 // UCSC UserID
 * * * * 2024 Winter CSE101 PA8 // Assignment Number
 * * * * Makefile // FileName
 * * * * Makefile for pa8 // Description
 * * * ***/

